listen_host=127.0.0.1
listen_port=9100

printer_host=192.168.1.50
printer_port=443

device=local_printer

verify_tls=0

http_timeout=20      # seconds (libcurl)
epos_timeout=10000   # milliseconds (printer)

debug_xml=0
debug_escpos=0
